site_name: DaSCH Organizational Handbook

nav:
    - General:
      - Introduction: general/index.md
    - Client Services:
      - Introduction: client-services/index.md
    - Engineering:
      - Introduction: engineering/index.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  features:
    - navigation.tabs
extra_css:
  - 'assets/style/theme.css'
